### ISSUE TITLE
Arbitrary selectors do not work in the utility pre-states with top-level `apply`

### ISSUE THREAD

**Issue by Dgcim1** [mr150/mlut#53]
I'm trying to use the `*` selector in pre-states, and then the others (`li`, `.class`). On the output I get nothing, or an error. Here's an example:

```scss
@use '../../node_modules/mlut/tools' as ml with (
  // my config here
);

@use 'includes/generic';
@use '../../node_modules/mlut/core' with (
  // my utilities here
);

@include ml.apply('*:c:+_O1_b');
```

`apply` doesn't do anything here. I've tried `=*:c:+_O1_b`, `.item:c:+_O1_b`, `=.item:c:+_O1_b`, but none of these work.

**Comment by mr150** [comment]
Hey! For most things to work in pre-states, you need to put `:` at the beginning: `:*:c:+_O1_b`, `:.item:c:+_O1_b`, etc. This is needed so that the parser can recognize pre-states among other utility components

By the way, to get similar behavior with a pseudo-class, you don't need to add `*` at the beginning: `:c:+_O1_b`) The output would be:
```scss
:checked + .\:c\:\+_O1_b::before {
  opacity: 1;
}
```

**Comment by Dgcim1** [comment]
Thanks, it's works fine now!
